version: "3"
services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-container
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${dns}:8000'
        registry_external_url 'http://${dns}:60000'
        registry['enable'] = true
    ports:
      - '8000:8000'
      - '8443:8443'
      - '50001:22'
      - '60000:60000'
    volumes:
      - '/docker-deploy/data/gitlab/config:/etc/gitlab'
      - '/docker-deploy/data/gitlab/logs:/var/log/gitlab'
      - '/docker-deploy/data/gitlab/data:/var/opt/gitlab'

  jenkins:
    build:
      context: '/docker-deploy/bin/jenkins'
      dockerfile: 'Dockerfile.jenkins'
      args:
        JENKINS_USER: '${jenkins_user}'
        JENKINS_PASS: '${jenkins_pass}'
    container_name: jenkins-container
    restart: always
    hostname: 'jenkins'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/docker-deploy/data/jenkins/home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

  sonarqube:
    image: 'sonarqube:8.4.1-community'
    ports:
      - '50002:9000'
    volumes:
      - '/docker-deploy/data/sonarqube/conf:/opt/sonarqube/conf'
      - '/docker-deploy/data/sonarqube/data:/opt/sonarqube/data'
      - '/docker-deploy/data/sonarqube/logs:/opt/sonarqube/logs'
      - '/docker-deploy/data/sonarqube/extensions:/opt/sonarqube/extensions'

  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    volumes:
      - '/docker-deploy/data/gitlab/runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'