version: "3"
services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-container
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
#        gitlab_rails['gitlab_shell_ssh_port'] = 50001
#        registry_external_url 'http://localhost:60000'
#        registry['enable'] = true
#        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    ports:
      - '8000:8000'
      - '8443:8443'
      - '50001:22'
#      - '60000:4567'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
#    networks:
#      - gitlab-network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-container
    restart: always
    hostname: 'jenkins'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

  sonarqube:
    image: 'sonarqube:8.4.1-community'
    ports:
      - '50002:9000'
    volumes:
      - 'sonarqube_conf:/opt/sonarqube/conf'
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_logs:/opt/sonarqube/logs'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'

#  sonarqube:
#    image: 'sonarqube:8.4.1-community'
#    container_name: sonar-container
#    restart: always
#    networks:
#      - sonarnet
#    environment:
#      - SONARQUBE_JDBC_USERNAME=sonar
#      - SONARQUBE_JDBC_PASSWORD=your-strong-password-here
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgressdb:5432/sonarqube
#    ports:
#      - "50002:9000"
#      - "50092:9092"
#    volumes:
#      - 'sonarqube_conf:/opt/sonarqube/conf'
#      - 'sonarqube_data:/opt/sonarqube/data'
#      - 'sonarqube_logs:/opt/sonarqube/logs'
#      - 'sonarqube_extensions:/opt/sonarqube/extensions'
#      - 'sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
#
#  postgressdb:
#    image: postgres:12.1
#    container_name: postgres-container
#    restart: always
#    networks:
#      - sonarnet
#    environment:
#      - POSTGRES_USER=sonar
#      - POSTGRES_PASSWORD=your-strong-password-here
#      - POSTGRES_DB=sonarqube
#    volumes:
#      - '/data/postgresql/sonarqube_db:/var/lib/postgresql'
#      - '/data/postgresql/postgresql_data:/var/lib/postgresql/data'

#  gitlab-runner1:
#    image: gitlab/gitlab-runner:latest
#    container_name: gitlab-runner1
#    hostname: gitlab-runner1
#    volumes:
#      - './gitlab-runner1-config:/etc/gitlab-runner:Z'
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    networks:
#      - gitlab-network

#networks:
#  gitlab-network:
#  sonarnet:
#    driver: bridge

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
#  sonarqube_bundled-plugins: